# Generated by Django 3.2.5 on 2021-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(help_text='Length of the short description should not exceed 30 characters', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Length of the post should not exceed 1000 characters.', max_length=1000),
        ),
    ]
