# Generated by Django 3.2.5 on 2021-07-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0003_auto_20210725_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['id'], 'verbose_name': 'Comment'},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='auhtor',
            new_name='author',
        ),
    ]
