# Generated by Django 3.2.5 on 2021-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0004_auto_20210725_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(null=True, to='pr.Comments'),
        ),
    ]
