# Generated by Django 3.2.5 on 2021-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0004_auto_20210728_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
