# Generated by Django 3.2.5 on 2021-08-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0005_alter_comments_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Length of the post should not exceed 1500 characters.', max_length=1500),
        ),
    ]
